### ISSUE TITLE
ext_localconf.php

### ISSUE THREAD

**Issue by sunfish** [t3brightside/embedassets#1]
Please remove use TYPO3\CMS\Core\Utility\ExtensionManagementUtility;
and use instead:
 $composerAutoloadFile = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('embedassets')
        . 'Resources/Private/PHP/autoload.php';

If several extension authors write the use command for namespaces in the ext_localconf.php or ext_tables.php file and these then occur more frequently due to caching in a merged file, this leads to a fatal error. 
Thank you for your work, which is appreciated

**Comment by t3brightside** [comment]
Thanks for the feedback!
As a best practice described here, it should be fine since v11.4?
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/BestPractises/ConfigurationFiles.html
